version: 2

sources:
  - name: raw
    schema: main
    description: "Source data from the Open Brewery DB dataset."
    tables:
      - name: raw_obdb_breweries
        description: "Raw brewery data as loaded from the source CSV."
      - name: raw_ba_json_data
        description: "Raw brewery data from the BA JSON source."
